### PR TITLE
style: Delete Job popover style and text adjustment

### PR DESCRIPTION
**Pull request by xyfy**
# Description

style: Delete Job popover style and text adjustment
1. ignore the exception and use Dns.GetHostName() directly
2. ignore .idea, .DS_Store for source manage
3. delete Job popover style and text adjustment

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by xyfy** [comment]
企业微信截图_9d24b9e2-a257-4a72-8298-a3e5d4a461c3

**Comment by xyfy** [comment]
企业微信截图_9de8f9cd-7048-49e8-a674-9740e2b2b70f

**Comment by xyfy** [comment]
image

**Comment by xyfy** [comment]
image

**Review by wzh425 — APPROVED** [review]
LGTM

**Pull request merged**
